#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip li add dummy0 type dummy
ip li set dummy0 up
ip addr add 10.0.0.13/32 dev dummy0
[ ! -d /run/bird ] && mkdir /run/bird
bird -d &
envsubst < /etc/scion/router49.toml > /etc/scion/_router49_.toml && router --config /etc/scion/_router49_.toml 2>&1 | rotatelogs -n 2 /var/log/scion-border-router.log 1M  &
echo "ROUTER_PID=$(pidof router)">>/etc/environment
echo "export ROUTER_PID=$(pidof router)">>/etc/profile
export ROUTER_PID=$(pidof router)

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

