#!/bin/bash
chmod +x /interface_setup
/interface_setup
envsubst < /etc/scion/dispatcher.toml > /etc/scion/_dispatcher_.toml && dispatcher --config /etc/scion/_dispatcher_.toml 2>&1 |  rotatelogs -n 2 /var/log/scion-dispatcher.log 1M  &
envsubst < /etc/scion/sciond.toml > /etc/scion/_sciond_.toml && daemon --config /etc/scion/_sciond_.toml  2>&1 | rotatelogs -n 2 /var/log/sciond.log 1M  &
echo "DAEMON_PID=$(pidof daemon)">>/etc/environment
echo "export DAEMON_PID=$(pidof daemon)">>/etc/profile
export DAEMON_PID=$(pidof daemon)
ip rou del default 2> /dev/null
ip route add default via 10.12.0.254 dev net0

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

