#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip li add dummy0 type dummy
ip li set dummy0 up
ip addr add 10.0.0.28/32 dev dummy0
[ ! -d /run/bird ] && mkdir /run/bird
bird -d &
router --config /etc/scion/router21.toml 2>&1 | rotatelogs -n 2 /var/log/scion-border-router.log 1M  &
echo "ROUTER_PID=$(pidof router)">>/etc/environment
echo "export ROUTER_PID=$(pidof router)">>/etc/profile
export ROUTER_PID=$(pidof router)
eval "$(ssh-agent -s)"
ssh-add /root/.ssh/id_ed25519
iptables -t nat -A POSTROUTING -j MASQUERADE


echo "development container started on: $HOSTNAME $CONTAINER_NAME"


echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

