#!/bin/bash
chmod +x /interface_setup
/interface_setup
dispatcher --config /etc/scion/dispatcher.toml 2>&1 |  rotatelogs -n 2 /var/log/scion-dispatcher.log 1M  &
daemon --config /etc/scion/sciond.toml  2>&1 | rotatelogs -n 2 /var/log/sciond.log 1M  &
control --config /etc/scion/cs1.toml  2>&1 | rotatelogs -n 2 /var/log/scion-control-service.log 1M  &
echo "CONTROL_PID=$(pidof control)">>/etc/environment
echo "export CONTROL_PID=$(pidof control)">>/etc/profile
export CONTROL_PID=$(pidof control)
echo "DAEMON_PID=$(pidof daemon)">>/etc/environment
echo "export DAEMON_PID=$(pidof daemon)">>/etc/profile
export DAEMON_PID=$(pidof daemon)
eval "$(ssh-agent -s)"
ssh-add /root/.ssh/id_ed25519
ip rou del default 2> /dev/null
ip route add default via 10.5.0.254 dev net0


echo "development container started on: $HOSTNAME $CONTAINER_NAME"


echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

